// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApiResponseStringOrUndefined
 */
export interface ApiResponseStringOrUndefined {
    /**
     * @type {string}
     * @memberof ApiResponseStringOrUndefined
     */
    data?: string;
    /**
     * @type {Array<string>}
     * @memberof ApiResponseStringOrUndefined
     */
    tags?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof ApiResponseStringOrUndefined
     */
    invalidatesTags?: Array<string>;
}
