// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SterioPlaylist,
} from './';

/**
 * @export
 * @interface ApiResponseSterioPlaylistArray
 */
export interface ApiResponseSterioPlaylistArray {
    /**
     * @type {Array<SterioPlaylist>}
     * @memberof ApiResponseSterioPlaylistArray
     */
    data: Array<SterioPlaylist>;
    /**
     * @type {Array<string>}
     * @memberof ApiResponseSterioPlaylistArray
     */
    tags?: Array<string>;
    /**
     * @type {Array<string>}
     * @memberof ApiResponseSterioPlaylistArray
     */
    invalidatesTags?: Array<string>;
}
