// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NodeId3NodeID3TagsUniqueFileIdentifierInner
 */
export interface NodeId3NodeID3TagsUniqueFileIdentifierInner {
    /**
     * Up to 64 bytes of binary data.  Providing more data will result in an undefined behaviour.
     * @type {string}
     * @memberof NodeId3NodeID3TagsUniqueFileIdentifierInner
     */
    identifier: string;
    /**
     * Must be non-empty.
     * @type {string}
     * @memberof NodeId3NodeID3TagsUniqueFileIdentifierInner
     */
    ownerIdentifier: string;
}
