// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    NodeId3NodeID3TagsEventTimingCodesKeyEventsInner,
} from './';

/**
 * ETCO frame
 * @export
 * @interface NodeId3NodeID3TagsEventTimingCodes
 */
export interface NodeId3NodeID3TagsEventTimingCodes {
    /**
     * @type {Array<NodeId3NodeID3TagsEventTimingCodesKeyEventsInner>}
     * @memberof NodeId3NodeID3TagsEventTimingCodes
     */
    keyEvents: Array<NodeId3NodeID3TagsEventTimingCodesKeyEventsInner>;
    /**
     * Absolute time unit:  {@link TagConstants.TimeStampFormat}
     * @type {number}
     * @memberof NodeId3NodeID3TagsEventTimingCodes
     */
    timeStampFormat: number;
}
