// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * See https://en.wikipedia.org/wiki/ID3#ID3v2_embedded_image_extension
 * @export
 * @interface NodeId3NodeID3TagsImageAnyOfType
 */
export interface NodeId3NodeID3TagsImageAnyOfType {
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsImageAnyOfType
     */
    name?: string;
    /**
     * {@link TagConstants.AttachedPicture.PictureType}
     * @type {number}
     * @memberof NodeId3NodeID3TagsImageAnyOfType
     */
    id: number;
}
