// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    NodeId3NodeID3TagsSynchronisedLyricsInnerSynchronisedTextInner,
} from './';

/**
 * @export
 * @interface NodeId3NodeID3TagsSynchronisedLyricsInner
 */
export interface NodeId3NodeID3TagsSynchronisedLyricsInner {
    /**
     * @type {Array<NodeId3NodeID3TagsSynchronisedLyricsInnerSynchronisedTextInner>}
     * @memberof NodeId3NodeID3TagsSynchronisedLyricsInner
     */
    synchronisedText: Array<NodeId3NodeID3TagsSynchronisedLyricsInnerSynchronisedTextInner>;
    /**
     * Content descriptor
     * @type {string}
     * @memberof NodeId3NodeID3TagsSynchronisedLyricsInner
     */
    shortText?: string;
    /**
     * {@link TagConstants.SynchronisedLyrics.ContentType}
     * @type {number}
     * @memberof NodeId3NodeID3TagsSynchronisedLyricsInner
     */
    contentType: number;
    /**
     * Absolute time unit:  {@link TagConstants.TimeStampFormat}
     * @type {number}
     * @memberof NodeId3NodeID3TagsSynchronisedLyricsInner
     */
    timeStampFormat: number;
    /**
     * 3 letter ISO 639-2 language code, for example: eng
     * @type {string}
     * @memberof NodeId3NodeID3TagsSynchronisedLyricsInner
     */
    language: string;
}
