// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Optional logo of the seller.
 * @export
 * @interface NodeId3NodeID3TagsCommercialFrameInnerSellerLogo
 */
export interface NodeId3NodeID3TagsCommercialFrameInnerSellerLogo {
    /**
     * Buffer containing the picture
     * @type {string}
     * @memberof NodeId3NodeID3TagsCommercialFrameInnerSellerLogo
     */
    picture: string;
    /**
     * Mime type of picture.  Only allowed values: image/jpeg, image/png, image/
     * @type {string}
     * @memberof NodeId3NodeID3TagsCommercialFrameInnerSellerLogo
     */
    mimeType?: string;
}
