// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NodeId3NodeID3TagsEventTimingCodesKeyEventsInner
 */
export interface NodeId3NodeID3TagsEventTimingCodesKeyEventsInner {
    /**
     * Absolute time in unit according to `timeStampFormat`.
     * @type {number}
     * @memberof NodeId3NodeID3TagsEventTimingCodesKeyEventsInner
     */
    timeStamp: number;
    /**
     * {@link TagConstants.EventTimingCodes.EventType}
     * @type {number}
     * @memberof NodeId3NodeID3TagsEventTimingCodesKeyEventsInner
     */
    type: number;
}
