// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NodeId3NodeID3TagsGeneralObjectInner
 */
export interface NodeId3NodeID3TagsGeneralObjectInner {
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsGeneralObjectInner
     */
    encapsulatedObject: string;
    /**
     * There may be more than one \"GEOB\" frame in each tag, but only  one with the same content description.
     * @type {string}
     * @memberof NodeId3NodeID3TagsGeneralObjectInner
     */
    contentDescription: string;
    /**
     * Case sensitive
     * @type {string}
     * @memberof NodeId3NodeID3TagsGeneralObjectInner
     */
    filename?: string;
    /**
     * Encoded with ISO-8859-1
     * @type {string}
     * @memberof NodeId3NodeID3TagsGeneralObjectInner
     */
    mimeType?: string;
}
