// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Describes how long the price is valid
 * @export
 * @interface NodeId3NodeID3TagsCommercialFrameInnerValidUntil
 */
export interface NodeId3NodeID3TagsCommercialFrameInnerValidUntil {
    /**
     * @type {number}
     * @memberof NodeId3NodeID3TagsCommercialFrameInnerValidUntil
     */
    day: number;
    /**
     * @type {number}
     * @memberof NodeId3NodeID3TagsCommercialFrameInnerValidUntil
     */
    month: number;
    /**
     * @type {number}
     * @memberof NodeId3NodeID3TagsCommercialFrameInnerValidUntil
     */
    year: number;
}
