// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    NodeId3NodeID3Tags,
} from './';

/**
 * @export
 * @interface NodeId3NodeID3TagsChapterInner
 */
export interface NodeId3NodeID3TagsChapterInner {
    /**
     * @type {NodeId3NodeID3Tags}
     * @memberof NodeId3NodeID3TagsChapterInner
     */
    tags?: NodeId3NodeID3Tags;
    /**
     * @type {number}
     * @memberof NodeId3NodeID3TagsChapterInner
     */
    startTimeMs: number;
    /**
     * @type {number}
     * @memberof NodeId3NodeID3TagsChapterInner
     */
    endTimeMs: number;
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsChapterInner
     */
    elementID: string;
}
