// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    NodeId3NodeID3TagsImageAnyOfType,
} from './';

/**
 * @export
 * @interface NodeId3NodeID3TagsImageAnyOf
 */
export interface NodeId3NodeID3TagsImageAnyOf {
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsImageAnyOf
     */
    imageBuffer: string;
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsImageAnyOf
     */
    description: string;
    /**
     * @type {NodeId3NodeID3TagsImageAnyOfType}
     * @memberof NodeId3NodeID3TagsImageAnyOf
     */
    type: NodeId3NodeID3TagsImageAnyOfType;
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsImageAnyOf
     */
    mime: string;
}
