// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    NodeId3NodeID3TagsCommercialFrameInnerPricesValue,
    NodeId3NodeID3TagsCommercialFrameInnerSellerLogo,
    NodeId3NodeID3TagsCommercialFrameInnerValidUntil,
} from './';

/**
 * @export
 * @interface NodeId3NodeID3TagsCommercialFrameInner
 */
export interface NodeId3NodeID3TagsCommercialFrameInner {
    /**
     * @type {NodeId3NodeID3TagsCommercialFrameInnerSellerLogo}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    sellerLogo?: NodeId3NodeID3TagsCommercialFrameInnerSellerLogo;
    /**
     * Short description of the product
     * @type {string}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    description?: string;
    /**
     * Name of the seller
     * @type {string}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    nameOfSeller?: string;
    /**
     * Describes how the audio is delivered when bought  {@link TagConstants.CommercialFrame.ReceivedAs}
     * @type {number}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    receivedAs: number;
    /**
     * @type {string}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    contactUrl?: string;
    /**
     * @type {NodeId3NodeID3TagsCommercialFrameInnerValidUntil}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    validUntil: NodeId3NodeID3TagsCommercialFrameInnerValidUntil;
    /**
     * Object containing price information.  Key is a three letter currency code according to ISO-4217 (e.g. EUR).  Value is a price string or number, e.g. 17.52
     * @type {{ [key: string]: NodeId3NodeID3TagsCommercialFrameInnerPricesValue; }}
     * @memberof NodeId3NodeID3TagsCommercialFrameInner
     */
    prices: { [key: string]: NodeId3NodeID3TagsCommercialFrameInnerPricesValue; };
}
