// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickSterioPlaylistIdOrName
 */
export interface PickSterioPlaylistIdOrName {
    /**
     * @type {string}
     * @memberof PickSterioPlaylistIdOrName
     */
    name?: string;
    /**
     * @type {string}
     * @memberof PickSterioPlaylistIdOrName
     */
    id: string;
}
