// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * External Url Object [](https://developer.spotify.com/web-api/object-model/)  Note that there might be other types available, it couldn\'t be found in the docs.
 * @export
 * @interface SpotifyApiExternalUrlObject
 */
export interface SpotifyApiExternalUrlObject {
    /**
     * @type {string}
     * @memberof SpotifyApiExternalUrlObject
     */
    spotify: string;
}
