// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SpotifyApiExternalUrlObject,
} from './';

/**
 * Simplified Artist Object [artist object (simplified)](https://developer.spotify.com/web-api/object-model/)
 * @export
 * @interface SpotifyApiArtistObjectSimplified
 */
export interface SpotifyApiArtistObjectSimplified {
    /**
     * The object type.
     * @type {string}
     * @memberof SpotifyApiArtistObjectSimplified
     */
    type: SpotifyApiArtistObjectSimplifiedTypeEnum;
    /**
     * A link to the Web API endpoint providing full details.
     * @type {string}
     * @memberof SpotifyApiArtistObjectSimplified
     */
    href: string;
    /**
     * @type {SpotifyApiExternalUrlObject}
     * @memberof SpotifyApiArtistObjectSimplified
     */
    external_urls: SpotifyApiExternalUrlObject;
    /**
     * The [Spotify URI](https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids).
     * @type {string}
     * @memberof SpotifyApiArtistObjectSimplified
     */
    uri: string;
    /**
     * The name of the artist.
     * @type {string}
     * @memberof SpotifyApiArtistObjectSimplified
     */
    name: string;
    /**
     * The [Spotify ID](https://developer.spotify.com/documentation/web-api/#spotify-uris-and-ids) for the artist.
     * @type {string}
     * @memberof SpotifyApiArtistObjectSimplified
     */
    id: string;
}

/**
 * @export
 * @enum {string}
 */
export enum SpotifyApiArtistObjectSimplifiedTypeEnum {
    Artist = 'artist'
}

