// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SpotifyApiArtistObjectSimplified,
} from './';

/**
 * @export
 * @interface SpotifyAlbumResponse
 */
export interface SpotifyAlbumResponse {
    /**
     * @type {string}
     * @memberof SpotifyAlbumResponse
     */
    id: string;
    /**
     * @type {string}
     * @memberof SpotifyAlbumResponse
     */
    name: string;
    /**
     * @type {Array<SpotifyApiArtistObjectSimplified>}
     * @memberof SpotifyAlbumResponse
     */
    artists: Array<SpotifyApiArtistObjectSimplified>;
    /**
     * @type {string}
     * @memberof SpotifyAlbumResponse
     */
    release_date: string;
}
