// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SterioAlbum
 */
export interface SterioAlbum {
    /**
     * @type {string}
     * @memberof SterioAlbum
     */
    youtubeMusicId: string;
    /**
     * @type {string}
     * @memberof SterioAlbum
     */
    youtubeMusicIteratee?: string;
    /**
     * @type {string}
     * @memberof SterioAlbum
     */
    youtubeId?: string;
    /**
     * @type {string}
     * @memberof SterioAlbum
     */
    youtubeIteratee?: string;
    /**
     * @type {string}
     * @memberof SterioAlbum
     */
    spotifyId?: string;
    /**
     * @type {string}
     * @memberof SterioAlbum
     */
    spotifyIteratee?: string;
    /**
     * @type {Array<number>}
     * @memberof SterioAlbum
     */
    songs?: Array<number>;
    /**
     * @type {boolean}
     * @memberof SterioAlbum
     */
    draft?: boolean;
}
