// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SterioPlaylist
 */
export interface SterioPlaylist {
    /**
     * @type {string}
     * @memberof SterioPlaylist
     */
    id: string;
    /**
     * @type {string}
     * @memberof SterioPlaylist
     */
    name?: string;
    /**
     * @type {{ [key: string]: Array<number>; }}
     * @memberof SterioPlaylist
     */
    items?: { [key: string]: Array<number>; };
}
