// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    NodeId3NodeID3Tags,
    PartialRecordAlbumOrSongPathStringChecksumString,
    PickSterioPlaylistIdOrName,
    SterioDuration,
    SterioSongFullChannel,
} from './';

/**
 * @export
 * @interface SterioSongFull
 */
export interface SterioSongFull {
    /**
     * @type {string}
     * @memberof SterioSongFull
     */
    youtubeMusicId: string;
    /**
     * @type {number}
     * @memberof SterioSongFull
     */
    index: number;
    /**
     * @type {string}
     * @memberof SterioSongFull
     */
    videoId: string;
    /**
     * @type {boolean}
     * @memberof SterioSongFull
     */
    patched: boolean;
    /**
     * @type {boolean}
     * @memberof SterioSongFull
     */
    included: boolean;
    /**
     * @type {SterioSongFullChannel}
     * @memberof SterioSongFull
     */
    channel?: SterioSongFullChannel;
    /**
     * @type {PartialRecordAlbumOrSongPathStringChecksumString}
     * @memberof SterioSongFull
     */
    artwork: PartialRecordAlbumOrSongPathStringChecksumString;
    /**
     * @type {SterioDuration}
     * @memberof SterioSongFull
     */
    duration?: SterioDuration;
    /**
     * @type {NodeId3NodeID3Tags}
     * @memberof SterioSongFull
     */
    tags: NodeId3NodeID3Tags;
    /**
     * @type {Array<PickSterioPlaylistIdOrName>}
     * @memberof SterioSongFull
     */
    playlists: Array<PickSterioPlaylistIdOrName>;
}
