// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SterioAlbumFullArtist,
    SterioAlbumFullThumbnailsInner,
    SterioSongFull,
} from './';

/**
 * @export
 * @interface SterioAlbumFull
 */
export interface SterioAlbumFull {
    /**
     * @type {string}
     * @memberof SterioAlbumFull
     */
    youtubeMusicId: string;
    /**
     * @type {string}
     * @memberof SterioAlbumFull
     */
    youtubeId?: string;
    /**
     * @type {string}
     * @memberof SterioAlbumFull
     */
    spotifyId?: string;
    /**
     * @type {SterioAlbumFullArtist}
     * @memberof SterioAlbumFull
     */
    artist: SterioAlbumFullArtist;
    /**
     * @type {string}
     * @memberof SterioAlbumFull
     */
    name: string;
    /**
     * @type {string}
     * @memberof SterioAlbumFull
     */
    playlistId: string;
    /**
     * @type {Array<SterioAlbumFullThumbnailsInner>}
     * @memberof SterioAlbumFull
     */
    thumbnails: Array<SterioAlbumFullThumbnailsInner>;
    /**
     * @type {number}
     * @memberof SterioAlbumFull
     */
    year: number;
    /**
     * @type {Array<SterioSongFull>}
     * @memberof SterioAlbumFull
     */
    songs: Array<SterioSongFull>;
}
