// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A thumbnail is an image representing a YouTube resource.
 * @export
 * @interface YoutubeV3Schema36Thumbnail
 */
export interface YoutubeV3Schema36Thumbnail {
    /**
     * (Optional) Height of the thumbnail image.
     * @type {number}
     * @memberof YoutubeV3Schema36Thumbnail
     */
    height?: number | null;
    /**
     * The thumbnail image\'s URL.
     * @type {string}
     * @memberof YoutubeV3Schema36Thumbnail
     */
    url?: string | null;
    /**
     * (Optional) Width of the thumbnail image.
     * @type {number}
     * @memberof YoutubeV3Schema36Thumbnail
     */
    width?: number | null;
}
