// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeV3Schema36PlaylistLocalization,
    YoutubeV3Schema36ThumbnailDetails,
} from './';

/**
 * Basic details about a playlist, including title, description and thumbnails.
 * @export
 * @interface YoutubeV3Schema36PlaylistSnippet
 */
export interface YoutubeV3Schema36PlaylistSnippet {
    /**
     * The ID that YouTube uses to uniquely identify the channel that published the playlist.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    channelId?: string | null;
    /**
     * The channel title of the channel that the video belongs to.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    channelTitle?: string | null;
    /**
     * The language of the playlist\'s default title and description.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    defaultLanguage?: string | null;
    /**
     * The playlist\'s description.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    description?: string | null;
    /**
     * @type {YoutubeV3Schema36PlaylistLocalization}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    localized?: YoutubeV3Schema36PlaylistLocalization;
    /**
     * The date and time that the playlist was created.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    publishedAt?: string | null;
    /**
     * Keyword tags associated with the playlist.
     * @type {Array<string>}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    tags?: Array<string> | null;
    /**
     * @type {YoutubeV3Schema36ThumbnailDetails}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    thumbnails?: YoutubeV3Schema36ThumbnailDetails;
    /**
     * Note: if the playlist has a custom thumbnail, this field will not be populated. The video id selected by the user that will be used as the thumbnail of this playlist. This field defaults to the first publicly viewable video in the playlist, if: 1. The user has never selected a video to be the thumbnail of the playlist. 2. The user selects a video to be the thumbnail, and then removes that video from the playlist. 3. The user selects a non-owned video to be the thumbnail, but that video becomes private, or gets deleted.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    thumbnailVideoId?: string | null;
    /**
     * The playlist\'s title.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistSnippet
     */
    title?: string | null;
}
