// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeV3Schema36PlaylistItem,
    YoutubeV3Schema36ThumbnailDetails,
} from './';

/**
 * @export
 * @interface YoutubePlaylist
 */
export interface YoutubePlaylist {
    /**
     * @type {string}
     * @memberof YoutubePlaylist
     */
    id: string;
    /**
     * @type {string}
     * @memberof YoutubePlaylist
     */
    title?: string;
    /**
     * @type {YoutubeV3Schema36ThumbnailDetails}
     * @memberof YoutubePlaylist
     */
    thumbnails?: YoutubeV3Schema36ThumbnailDetails;
    /**
     * @type {Array<YoutubeV3Schema36PlaylistItem>}
     * @memberof YoutubePlaylist
     */
    items: Array<YoutubeV3Schema36PlaylistItem>;
}
