// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeMusicAlbumResponseArtist,
    YoutubeMusicSongResponseAlbum,
} from './';

/**
 * @export
 * @interface YoutubeMusicSongResponse
 */
export interface YoutubeMusicSongResponse {
    /**
     * @type {string}
     * @memberof YoutubeMusicSongResponse
     */
    videoId: string;
    /**
     * @type {string}
     * @memberof YoutubeMusicSongResponse
     */
    name: string;
    /**
     * @type {YoutubeMusicSongResponseAlbum}
     * @memberof YoutubeMusicSongResponse
     */
    album: YoutubeMusicSongResponseAlbum | null;
    /**
     * @type {YoutubeMusicAlbumResponseArtist}
     * @memberof YoutubeMusicSongResponse
     */
    artist: YoutubeMusicAlbumResponseArtist;
    /**
     * @type {boolean}
     * @memberof YoutubeMusicSongResponse
     */
    isSaved: boolean;
}
