// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeV3Schema36Thumbnail,
} from './';

/**
 * Internal representation of thumbnails for a YouTube resource.
 * @export
 * @interface YoutubeV3Schema36ThumbnailDetails
 */
export interface YoutubeV3Schema36ThumbnailDetails {
    /**
     * @type {YoutubeV3Schema36Thumbnail}
     * @memberof YoutubeV3Schema36ThumbnailDetails
     */
    _default?: YoutubeV3Schema36Thumbnail;
    /**
     * @type {YoutubeV3Schema36Thumbnail}
     * @memberof YoutubeV3Schema36ThumbnailDetails
     */
    high?: YoutubeV3Schema36Thumbnail;
    /**
     * @type {YoutubeV3Schema36Thumbnail}
     * @memberof YoutubeV3Schema36ThumbnailDetails
     */
    maxres?: YoutubeV3Schema36Thumbnail;
    /**
     * @type {YoutubeV3Schema36Thumbnail}
     * @memberof YoutubeV3Schema36ThumbnailDetails
     */
    medium?: YoutubeV3Schema36Thumbnail;
    /**
     * @type {YoutubeV3Schema36Thumbnail}
     * @memberof YoutubeV3Schema36ThumbnailDetails
     */
    standard?: YoutubeV3Schema36Thumbnail;
}
