// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Information about the playlist item\'s privacy status.
 * @export
 * @interface YoutubeV3Schema36PlaylistItemStatus
 */
export interface YoutubeV3Schema36PlaylistItemStatus {
    /**
     * This resource\'s privacy status.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemStatus
     */
    privacyStatus?: string | null;
}
