// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeV3Schema36ResourceId,
    YoutubeV3Schema36ThumbnailDetails,
} from './';

/**
 * Basic details about a playlist, including title, description and thumbnails. Basic details of a YouTube Playlist item provided by the author. Next ID: 15
 * @export
 * @interface YoutubeV3Schema36PlaylistItemSnippet
 */
export interface YoutubeV3Schema36PlaylistItemSnippet {
    /**
     * The ID that YouTube uses to uniquely identify the user that added the item to the playlist.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    channelId?: string | null;
    /**
     * Channel title for the channel that the playlist item belongs to.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    channelTitle?: string | null;
    /**
     * The item\'s description.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    description?: string | null;
    /**
     * The ID that YouTube uses to uniquely identify thGe playlist that the playlist item is in.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    playlistId?: string | null;
    /**
     * The order in which the item appears in the playlist. The value uses a zero-based index, so the first item has a position of 0, the second item has a position of 1, and so forth.
     * @type {number}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    position?: number | null;
    /**
     * The date and time that the item was added to the playlist.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    publishedAt?: string | null;
    /**
     * @type {YoutubeV3Schema36ResourceId}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    resourceId?: YoutubeV3Schema36ResourceId;
    /**
     * @type {YoutubeV3Schema36ThumbnailDetails}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    thumbnails?: YoutubeV3Schema36ThumbnailDetails;
    /**
     * The item\'s title.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    title?: string | null;
    /**
     * Channel id for the channel this video belongs to.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    videoOwnerChannelId?: string | null;
    /**
     * Channel title for the channel this video belongs to.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemSnippet
     */
    videoOwnerChannelTitle?: string | null;
}
