// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface YoutubeV3Schema36PlaylistItemContentDetails
 */
export interface YoutubeV3Schema36PlaylistItemContentDetails {
    /**
     * The time, measured in seconds from the start of the video, when the video should stop playing. (The playlist owner can specify the times when the video should start and stop playing when the video is played in the context of the playlist.) By default, assume that the video.endTime is the end of the video.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemContentDetails
     */
    endAt?: string | null;
    /**
     * A user-generated note for this item.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemContentDetails
     */
    note?: string | null;
    /**
     * The time, measured in seconds from the start of the video, when the video should start playing. (The playlist owner can specify the times when the video should start and stop playing when the video is played in the context of the playlist.) The default value is 0.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemContentDetails
     */
    startAt?: string | null;
    /**
     * The ID that YouTube uses to uniquely identify a video. To retrieve the video resource, set the id query parameter to this value in your API request.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemContentDetails
     */
    videoId?: string | null;
    /**
     * The date and time that the video was published to YouTube.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItemContentDetails
     */
    videoPublishedAt?: string | null;
}
