// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeV3Schema36PlaylistContentDetails,
    YoutubeV3Schema36PlaylistLocalization,
    YoutubeV3Schema36PlaylistPlayer,
    YoutubeV3Schema36PlaylistSnippet,
    YoutubeV3Schema36PlaylistStatus,
} from './';

/**
 * A *playlist* resource represents a YouTube playlist. A playlist is a collection of videos that can be viewed sequentially and shared with other users. A playlist can contain up to 200 videos, and YouTube does not limit the number of playlists that each user creates. By default, playlists are publicly visible to other users, but playlists can be public or private. YouTube also uses playlists to identify special collections of videos for a channel, such as: - uploaded videos - favorite videos - positively rated (liked) videos - watch history - watch later To be more specific, these lists are associated with a channel, which is a collection of a person, group, or company\'s videos, playlists, and other YouTube information. You can retrieve the playlist IDs for each of these lists from the channel resource for a given channel. You can then use the playlistItems.list method to retrieve any of those lists. You can also add or remove items from those lists by calling the playlistItems.insert and playlistItems.delete methods.
 * @export
 * @interface YoutubeV3Schema36Playlist
 */
export interface YoutubeV3Schema36Playlist {
    /**
     * @type {YoutubeV3Schema36PlaylistContentDetails}
     * @memberof YoutubeV3Schema36Playlist
     */
    contentDetails?: YoutubeV3Schema36PlaylistContentDetails;
    /**
     * Etag of this resource.
     * @type {string}
     * @memberof YoutubeV3Schema36Playlist
     */
    etag?: string | null;
    /**
     * The ID that YouTube uses to uniquely identify the playlist.
     * @type {string}
     * @memberof YoutubeV3Schema36Playlist
     */
    id?: string | null;
    /**
     * Identifies what kind of resource this is. Value: the fixed string \"youtube#playlist\".
     * @type {string}
     * @memberof YoutubeV3Schema36Playlist
     */
    kind?: string | null;
    /**
     * Localizations for different languages
     * @type {{ [key: string]: YoutubeV3Schema36PlaylistLocalization; }}
     * @memberof YoutubeV3Schema36Playlist
     */
    localizations?: { [key: string]: YoutubeV3Schema36PlaylistLocalization; } | null;
    /**
     * @type {YoutubeV3Schema36PlaylistPlayer}
     * @memberof YoutubeV3Schema36Playlist
     */
    player?: YoutubeV3Schema36PlaylistPlayer;
    /**
     * @type {YoutubeV3Schema36PlaylistSnippet}
     * @memberof YoutubeV3Schema36Playlist
     */
    snippet?: YoutubeV3Schema36PlaylistSnippet;
    /**
     * @type {YoutubeV3Schema36PlaylistStatus}
     * @memberof YoutubeV3Schema36Playlist
     */
    status?: YoutubeV3Schema36PlaylistStatus;
}
