// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Playlist localization setting
 * @export
 * @interface YoutubeV3Schema36PlaylistLocalization
 */
export interface YoutubeV3Schema36PlaylistLocalization {
    /**
     * The localized strings for playlist\'s description.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistLocalization
     */
    description?: string | null;
    /**
     * The localized strings for playlist\'s title.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistLocalization
     */
    title?: string | null;
}
