// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A resource id is a generic reference that points to another YouTube resource.
 * @export
 * @interface YoutubeV3Schema36ResourceId
 */
export interface YoutubeV3Schema36ResourceId {
    /**
     * The ID that YouTube uses to uniquely identify the referred resource, if that resource is a channel. This property is only present if the resourceId.kind value is youtube#channel.
     * @type {string}
     * @memberof YoutubeV3Schema36ResourceId
     */
    channelId?: string | null;
    /**
     * The type of the API resource.
     * @type {string}
     * @memberof YoutubeV3Schema36ResourceId
     */
    kind?: string | null;
    /**
     * The ID that YouTube uses to uniquely identify the referred resource, if that resource is a playlist. This property is only present if the resourceId.kind value is youtube#playlist.
     * @type {string}
     * @memberof YoutubeV3Schema36ResourceId
     */
    playlistId?: string | null;
    /**
     * The ID that YouTube uses to uniquely identify the referred resource, if that resource is a video. This property is only present if the resourceId.kind value is youtube#video.
     * @type {string}
     * @memberof YoutubeV3Schema36ResourceId
     */
    videoId?: string | null;
}
