// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface YoutubeV3Schema36PlaylistPlayer
 */
export interface YoutubeV3Schema36PlaylistPlayer {
    /**
     * An <iframe\\> tag that embeds a player that will play the playlist.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistPlayer
     */
    embedHtml?: string | null;
}
