// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    YoutubeV3Schema36PlaylistItemContentDetails,
    YoutubeV3Schema36PlaylistItemSnippet,
    YoutubeV3Schema36PlaylistItemStatus,
} from './';

/**
 * A *playlistItem* resource identifies another resource, such as a video, that is included in a playlist. In addition, the playlistItem resource contains details about the included resource that pertain specifically to how that resource is used in that playlist. YouTube uses playlists to identify special collections of videos for a channel, such as: - uploaded videos - favorite videos - positively rated (liked) videos - watch history - watch later To be more specific, these lists are associated with a channel, which is a collection of a person, group, or company\'s videos, playlists, and other YouTube information. You can retrieve the playlist IDs for each of these lists from the channel resource for a given channel. You can then use the playlistItems.list method to retrieve any of those lists. You can also add or remove items from those lists by calling the playlistItems.insert and playlistItems.delete methods. For example, if a user gives a positive rating to a video, you would insert that video into the liked videos playlist for that user\'s channel.
 * @export
 * @interface YoutubeV3Schema36PlaylistItem
 */
export interface YoutubeV3Schema36PlaylistItem {
    /**
     * @type {YoutubeV3Schema36PlaylistItemContentDetails}
     * @memberof YoutubeV3Schema36PlaylistItem
     */
    contentDetails?: YoutubeV3Schema36PlaylistItemContentDetails;
    /**
     * Etag of this resource.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItem
     */
    etag?: string | null;
    /**
     * The ID that YouTube uses to uniquely identify the playlist item.
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItem
     */
    id?: string | null;
    /**
     * Identifies what kind of resource this is. Value: the fixed string \"youtube#playlistItem\".
     * @type {string}
     * @memberof YoutubeV3Schema36PlaylistItem
     */
    kind?: string | null;
    /**
     * @type {YoutubeV3Schema36PlaylistItemSnippet}
     * @memberof YoutubeV3Schema36PlaylistItem
     */
    snippet?: YoutubeV3Schema36PlaylistItemSnippet;
    /**
     * @type {YoutubeV3Schema36PlaylistItemStatus}
     * @memberof YoutubeV3Schema36PlaylistItem
     */
    status?: YoutubeV3Schema36PlaylistItemStatus;
}
