// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface YoutubeV3Schema36PlaylistContentDetails
 */
export interface YoutubeV3Schema36PlaylistContentDetails {
    /**
     * The number of videos in the playlist.
     * @type {number}
     * @memberof YoutubeV3Schema36PlaylistContentDetails
     */
    itemCount?: number | null;
}
