// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface YoutubeMusicAlbumResponseArtist
 */
export interface YoutubeMusicAlbumResponseArtist {
    /**
     * @type {string}
     * @memberof YoutubeMusicAlbumResponseArtist
     */
    name: string;
    /**
     * @type {string}
     * @memberof YoutubeMusicAlbumResponseArtist
     */
    artistId: string | null;
}
