// tslint:disable
/**
 * @cascateer/sterio-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    ApiResponseSpotifyAlbumResponse,
    ApiResponseSpotifyAlbumResponseArray,
    ApiResponseSterioAlbum,
    ApiResponseSterioAlbumFull,
    ApiResponseSterioPlaylist,
    ApiResponseSterioPlaylistArray,
    ApiResponseString,
    ApiResponseStringArray,
    ApiResponseStringOrUndefined,
    ApiResponseVoid,
    ApiResponseYoutubeMusicAlbumResponse,
    ApiResponseYoutubeMusicAlbumResponseArray,
    ApiResponseYoutubeMusicArtistResponseArray,
    ApiResponseYoutubeMusicSongResponseArray,
    ApiResponseYoutubePlaylistArray,
    SterioAlbum,
    SterioCompilerConfig,
    SterioPlaylist,
} from '../models';

export interface CompileAlbumsRequest {
    sterioCompilerConfig: SterioCompilerConfig;
}

export interface DeleteAlbumRequest {
    id: string;
}

export interface GetAlbumRequest {
    id: string;
}

export interface GetAlbumFullRequest {
    id: string;
}

export interface GetAlbumResourceConflictsRequest {
    id: string;
}

export interface GetPlaylistRequest {
    id: string;
}

export interface GetSpotifyAlbumRequest {
    id: string;
}

export interface GetSpotifyAlbumsRequest {
    q: string;
}

export interface GetYoutubeMusicAlbumRequest {
    id: string;
}

export interface GetYoutubePlaylistsRequest {
    ids: string;
}

export interface SearchYoutubeMusicAlbumsRequest {
    q: string;
}

export interface SearchYoutubeMusicArtistSongsRequest {
    id: string;
}

export interface SearchYoutubeMusicArtistsRequest {
    q: string;
}

export interface UpdateAlbumRequest {
    sterioAlbum: SterioAlbum;
}

export interface UpdatePlaylistRequest {
    sterioPlaylist: SterioPlaylist;
}

/**
 * no description
 */
export class DefaultApi extends BaseAPI {

    /**
     */
    compileAlbums({ sterioCompilerConfig }: CompileAlbumsRequest): Observable<ApiResponseString>
    compileAlbums({ sterioCompilerConfig }: CompileAlbumsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseString>>
    compileAlbums({ sterioCompilerConfig }: CompileAlbumsRequest, opts?: OperationOpts): Observable<ApiResponseString | AjaxResponse<ApiResponseString>> {
        throwIfNullOrUndefined(sterioCompilerConfig, 'sterioCompilerConfig', 'compileAlbums');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ApiResponseString>({
            url: '/sterio/albums/compilation',
            method: 'POST',
            headers,
            body: sterioCompilerConfig,
        }, opts?.responseOpts);
    };

    /**
     */
    deleteAlbum({ id }: DeleteAlbumRequest): Observable<ApiResponseStringOrUndefined>
    deleteAlbum({ id }: DeleteAlbumRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseStringOrUndefined>>
    deleteAlbum({ id }: DeleteAlbumRequest, opts?: OperationOpts): Observable<ApiResponseStringOrUndefined | AjaxResponse<ApiResponseStringOrUndefined>> {
        throwIfNullOrUndefined(id, 'id', 'deleteAlbum');

        return this.request<ApiResponseStringOrUndefined>({
            url: '/sterio/album/{id}'.replace('{id}', encodeURI(id)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     */
    getAlbum({ id }: GetAlbumRequest): Observable<ApiResponseSterioAlbum>
    getAlbum({ id }: GetAlbumRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseSterioAlbum>>
    getAlbum({ id }: GetAlbumRequest, opts?: OperationOpts): Observable<ApiResponseSterioAlbum | AjaxResponse<ApiResponseSterioAlbum>> {
        throwIfNullOrUndefined(id, 'id', 'getAlbum');

        return this.request<ApiResponseSterioAlbum>({
            url: '/sterio/album/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getAlbumFull({ id }: GetAlbumFullRequest): Observable<ApiResponseSterioAlbumFull>
    getAlbumFull({ id }: GetAlbumFullRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseSterioAlbumFull>>
    getAlbumFull({ id }: GetAlbumFullRequest, opts?: OperationOpts): Observable<ApiResponseSterioAlbumFull | AjaxResponse<ApiResponseSterioAlbumFull>> {
        throwIfNullOrUndefined(id, 'id', 'getAlbumFull');

        return this.request<ApiResponseSterioAlbumFull>({
            url: '/sterio/albumFull/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getAlbumIds(): Observable<ApiResponseStringArray>
    getAlbumIds(opts?: OperationOpts): Observable<AjaxResponse<ApiResponseStringArray>>
    getAlbumIds(opts?: OperationOpts): Observable<ApiResponseStringArray | AjaxResponse<ApiResponseStringArray>> {
        return this.request<ApiResponseStringArray>({
            url: '/sterio/albumsIds',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getAlbumResourceConflicts({ id }: GetAlbumResourceConflictsRequest): Observable<ApiResponseString>
    getAlbumResourceConflicts({ id }: GetAlbumResourceConflictsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseString>>
    getAlbumResourceConflicts({ id }: GetAlbumResourceConflictsRequest, opts?: OperationOpts): Observable<ApiResponseString | AjaxResponse<ApiResponseString>> {
        throwIfNullOrUndefined(id, 'id', 'getAlbumResourceConflicts');

        return this.request<ApiResponseString>({
            url: '/sterio/album/{id}/resource/conflicts'.replace('{id}', encodeURI(id)),
            method: 'POST',
        }, opts?.responseOpts);
    };

    /**
     */
    getPlaylist({ id }: GetPlaylistRequest): Observable<ApiResponseSterioPlaylist>
    getPlaylist({ id }: GetPlaylistRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseSterioPlaylist>>
    getPlaylist({ id }: GetPlaylistRequest, opts?: OperationOpts): Observable<ApiResponseSterioPlaylist | AjaxResponse<ApiResponseSterioPlaylist>> {
        throwIfNullOrUndefined(id, 'id', 'getPlaylist');

        return this.request<ApiResponseSterioPlaylist>({
            url: '/sterio/playlist/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getPlaylists(): Observable<ApiResponseSterioPlaylistArray>
    getPlaylists(opts?: OperationOpts): Observable<AjaxResponse<ApiResponseSterioPlaylistArray>>
    getPlaylists(opts?: OperationOpts): Observable<ApiResponseSterioPlaylistArray | AjaxResponse<ApiResponseSterioPlaylistArray>> {
        return this.request<ApiResponseSterioPlaylistArray>({
            url: '/sterio/playlists',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getSpotifyAlbum({ id }: GetSpotifyAlbumRequest): Observable<ApiResponseSpotifyAlbumResponse>
    getSpotifyAlbum({ id }: GetSpotifyAlbumRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseSpotifyAlbumResponse>>
    getSpotifyAlbum({ id }: GetSpotifyAlbumRequest, opts?: OperationOpts): Observable<ApiResponseSpotifyAlbumResponse | AjaxResponse<ApiResponseSpotifyAlbumResponse>> {
        throwIfNullOrUndefined(id, 'id', 'getSpotifyAlbum');

        return this.request<ApiResponseSpotifyAlbumResponse>({
            url: '/sterio/spotify/album/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getSpotifyAlbums({ q }: GetSpotifyAlbumsRequest): Observable<ApiResponseSpotifyAlbumResponseArray>
    getSpotifyAlbums({ q }: GetSpotifyAlbumsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseSpotifyAlbumResponseArray>>
    getSpotifyAlbums({ q }: GetSpotifyAlbumsRequest, opts?: OperationOpts): Observable<ApiResponseSpotifyAlbumResponseArray | AjaxResponse<ApiResponseSpotifyAlbumResponseArray>> {
        throwIfNullOrUndefined(q, 'q', 'getSpotifyAlbums');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'q': q,
        };

        return this.request<ApiResponseSpotifyAlbumResponseArray>({
            url: '/sterio/spotify/albums',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    getYoutubeMusicAlbum({ id }: GetYoutubeMusicAlbumRequest): Observable<ApiResponseYoutubeMusicAlbumResponse>
    getYoutubeMusicAlbum({ id }: GetYoutubeMusicAlbumRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseYoutubeMusicAlbumResponse>>
    getYoutubeMusicAlbum({ id }: GetYoutubeMusicAlbumRequest, opts?: OperationOpts): Observable<ApiResponseYoutubeMusicAlbumResponse | AjaxResponse<ApiResponseYoutubeMusicAlbumResponse>> {
        throwIfNullOrUndefined(id, 'id', 'getYoutubeMusicAlbum');

        return this.request<ApiResponseYoutubeMusicAlbumResponse>({
            url: '/sterio/youtube-music/album/{id}'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    getYoutubePlaylists({ ids }: GetYoutubePlaylistsRequest): Observable<ApiResponseYoutubePlaylistArray>
    getYoutubePlaylists({ ids }: GetYoutubePlaylistsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseYoutubePlaylistArray>>
    getYoutubePlaylists({ ids }: GetYoutubePlaylistsRequest, opts?: OperationOpts): Observable<ApiResponseYoutubePlaylistArray | AjaxResponse<ApiResponseYoutubePlaylistArray>> {
        throwIfNullOrUndefined(ids, 'ids', 'getYoutubePlaylists');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'ids': ids,
        };

        return this.request<ApiResponseYoutubePlaylistArray>({
            url: '/sterio/youtube/playlists',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    searchYoutubeMusicAlbums({ q }: SearchYoutubeMusicAlbumsRequest): Observable<ApiResponseYoutubeMusicAlbumResponseArray>
    searchYoutubeMusicAlbums({ q }: SearchYoutubeMusicAlbumsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseYoutubeMusicAlbumResponseArray>>
    searchYoutubeMusicAlbums({ q }: SearchYoutubeMusicAlbumsRequest, opts?: OperationOpts): Observable<ApiResponseYoutubeMusicAlbumResponseArray | AjaxResponse<ApiResponseYoutubeMusicAlbumResponseArray>> {
        throwIfNullOrUndefined(q, 'q', 'searchYoutubeMusicAlbums');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'q': q,
        };

        return this.request<ApiResponseYoutubeMusicAlbumResponseArray>({
            url: '/sterio/youtube-music/albums/search',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    searchYoutubeMusicArtistSongs({ id }: SearchYoutubeMusicArtistSongsRequest): Observable<ApiResponseYoutubeMusicSongResponseArray>
    searchYoutubeMusicArtistSongs({ id }: SearchYoutubeMusicArtistSongsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseYoutubeMusicSongResponseArray>>
    searchYoutubeMusicArtistSongs({ id }: SearchYoutubeMusicArtistSongsRequest, opts?: OperationOpts): Observable<ApiResponseYoutubeMusicSongResponseArray | AjaxResponse<ApiResponseYoutubeMusicSongResponseArray>> {
        throwIfNullOrUndefined(id, 'id', 'searchYoutubeMusicArtistSongs');

        return this.request<ApiResponseYoutubeMusicSongResponseArray>({
            url: '/sterio/youtube-music/artist/{id}/songs'.replace('{id}', encodeURI(id)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    searchYoutubeMusicArtists({ q }: SearchYoutubeMusicArtistsRequest): Observable<ApiResponseYoutubeMusicArtistResponseArray>
    searchYoutubeMusicArtists({ q }: SearchYoutubeMusicArtistsRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseYoutubeMusicArtistResponseArray>>
    searchYoutubeMusicArtists({ q }: SearchYoutubeMusicArtistsRequest, opts?: OperationOpts): Observable<ApiResponseYoutubeMusicArtistResponseArray | AjaxResponse<ApiResponseYoutubeMusicArtistResponseArray>> {
        throwIfNullOrUndefined(q, 'q', 'searchYoutubeMusicArtists');

        const query: HttpQuery = { // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            'q': q,
        };

        return this.request<ApiResponseYoutubeMusicArtistResponseArray>({
            url: '/sterio/youtube-music/artists/search',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     */
    updateAlbum({ sterioAlbum }: UpdateAlbumRequest): Observable<ApiResponseVoid>
    updateAlbum({ sterioAlbum }: UpdateAlbumRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseVoid>>
    updateAlbum({ sterioAlbum }: UpdateAlbumRequest, opts?: OperationOpts): Observable<ApiResponseVoid | AjaxResponse<ApiResponseVoid>> {
        throwIfNullOrUndefined(sterioAlbum, 'sterioAlbum', 'updateAlbum');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ApiResponseVoid>({
            url: '/sterio/album',
            method: 'PATCH',
            headers,
            body: sterioAlbum,
        }, opts?.responseOpts);
    };

    /**
     */
    updatePlaylist({ sterioPlaylist }: UpdatePlaylistRequest): Observable<ApiResponseVoid>
    updatePlaylist({ sterioPlaylist }: UpdatePlaylistRequest, opts?: OperationOpts): Observable<AjaxResponse<ApiResponseVoid>>
    updatePlaylist({ sterioPlaylist }: UpdatePlaylistRequest, opts?: OperationOpts): Observable<ApiResponseVoid | AjaxResponse<ApiResponseVoid>> {
        throwIfNullOrUndefined(sterioPlaylist, 'sterioPlaylist', 'updatePlaylist');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ApiResponseVoid>({
            url: '/sterio/playlist',
            method: 'PATCH',
            headers,
            body: sterioPlaylist,
        }, opts?.responseOpts);
    };

}
